spring:
  application:
    name: innoBackend
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.yandex.ru
    port: 587
    username: "arklual@yandex.ru"
    password: "mqsldksdeujnsokd"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  secret: secret